-- Run in Supabase SQL Editor. The client only uses the anon key; RLS is mandatory.
create table if not exists public.user_progress (
  user_id uuid primary key references auth.users(id) on delete cascade,
  quiz_history jsonb not null default '[]'::jsonb,
  flashcard_progress jsonb not null default '{}'::jsonb,
  stats jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
alter table public.user_progress enable row level security;
create policy "Users read own progress" on public.user_progress for select using (auth.uid() = user_id);
create policy "Users insert own progress" on public.user_progress for insert with check (auth.uid() = user_id);
create policy "Users update own progress" on public.user_progress for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  element_symbol text not null,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now(),
  parent_id bigint references public.comments(id) on delete cascade
);
alter table public.comments enable row level security;
create policy "Anyone reads comments" on public.comments for select using (true);
create policy "Users create comments" on public.comments for insert to authenticated with check (auth.uid() = user_id);
create policy "Users delete own comments" on public.comments for delete to authenticated using (auth.uid() = user_id);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (char_length(reason) between 1 and 500),
  created_at timestamptz not null default now()
);
alter table public.reports enable row level security;
create policy "Users submit reports" on public.reports for insert to authenticated with check (auth.uid() = user_id);

alter table public.comments replica identity full;
alter publication supabase_realtime add table public.comments;
